# Generated by Django 4.2.7 on 2023-11-21 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PerevalAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parent', models.IntegerField()),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SprActivitiesTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=128, unique=True)),
                ('full_name', models.CharField(max_length=128)),
                ('phone', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perevals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beautyTitle', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('other_titles', models.CharField(max_length=200)),
                ('connect', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('NW', 'Новый'), ('PN', 'Взято в работу'), ('AC', 'Успешно'), ('RJ', 'Отклонено')], default='NW', max_length=2)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('winter_level', models.CharField(max_length=10)),
                ('summer_level', models.CharField(max_length=10)),
                ('autumn_level', models.CharField(max_length=10)),
                ('spring_level', models.CharField(max_length=10)),
                ('coord_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perevals.coords')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perevals.users')),
            ],
        ),
        migrations.CreateModel(
            name='PerevalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perevals.images')),
                ('pereval_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perevals.perevals')),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='pereval_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perevals.perevals'),
        ),
    ]
