# Generated by Django 4.2.7 on 2023-11-23 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(max_length=20, verbose_name='Широта')),
                ('longitude', models.FloatField(max_length=20, verbose_name='Долгота')),
                ('height', models.IntegerField(verbose_name='Высота')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название изображения')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('image', models.ImageField(upload_to='images', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(choices=[('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б'), ('4a', '4А'), ('4b', '4Б'), ('5a', '5А'), ('5b', '5Б'), ('6a', '6А'), ('6b', '6Б')], max_length=2, verbose_name='Зима')),
                ('summer', models.CharField(choices=[('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б'), ('4a', '4А'), ('4b', '4Б'), ('5a', '5А'), ('5b', '5Б'), ('6a', '6А'), ('6b', '6Б')], max_length=2, verbose_name='Лето')),
                ('autumn', models.CharField(choices=[('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б'), ('4a', '4А'), ('4b', '4Б'), ('5a', '5А'), ('5b', '5Б'), ('6a', '6А'), ('6b', '6Б')], max_length=2, verbose_name='Осень')),
                ('spring', models.CharField(choices=[('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б'), ('4a', '4А'), ('4b', '4Б'), ('5a', '5А'), ('5b', '5Б'), ('6a', '6А'), ('6b', '6Б')], max_length=2, verbose_name='Весна')),
            ],
        ),
        migrations.CreateModel(
            name='PerevalAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название горы')),
            ],
        ),
        migrations.CreateModel(
            name='SprActivitiesTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('MN', 'Горный'), ('HK', 'Пеший'), ('SK', 'Лыжный'), ('BK', 'Велосипедный'), ('MH', 'Горно-пеший')], max_length=128, verbose_name='Тип похода')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=128, verbose_name='Полное имя')),
                ('phone', models.IntegerField(unique=True, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Perevals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beautyTitle', models.CharField(max_length=200, verbose_name='Общее название')),
                ('title', models.CharField(max_length=200, verbose_name='Название перевала')),
                ('other_titles', models.CharField(max_length=200)),
                ('connect', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('NW', 'Новый'), ('PN', 'Взято в работу'), ('AC', 'Успешно'), ('RJ', 'Отклонено')], default='NW', max_length=2)),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('coord_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perevals.coords')),
                ('level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perevals.level')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perevals.users')),
            ],
        ),
        migrations.CreateModel(
            name='PerevalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perevals.images')),
                ('pereval_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perevals.perevals')),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='pereval_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perevals.perevals'),
        ),
    ]
