# Generated by Django 4.2.7 on 2023-11-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perevals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perevals',
            old_name='beautyTitle',
            new_name='beauty_title',
        ),
    ]
