# Generated by Django 4.2.7 on 2023-11-23 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perevals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(choices=[('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б'), ('4a', '4А'), ('4b', '4Б'), ('5a', '5А'), ('5b', '5Б'), ('6a', '6А'), ('6b', '6Б')], max_length=2, verbose_name='Зима')),
                ('summer', models.CharField(choices=[('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б'), ('4a', '4А'), ('4b', '4Б'), ('5a', '5А'), ('5b', '5Б'), ('6a', '6А'), ('6b', '6Б')], max_length=2, verbose_name='Лето')),
                ('autumn', models.CharField(choices=[('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б'), ('4a', '4А'), ('4b', '4Б'), ('5a', '5А'), ('5b', '5Б'), ('6a', '6А'), ('6b', '6Б')], max_length=2, verbose_name='Осень')),
                ('spring', models.CharField(choices=[('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б'), ('4a', '4А'), ('4b', '4Б'), ('5a', '5А'), ('5b', '5Б'), ('6a', '6А'), ('6b', '6Б')], max_length=2, verbose_name='Весна')),
            ],
        ),
        migrations.RemoveField(
            model_name='perevalareas',
            name='id_parent',
        ),
        migrations.RemoveField(
            model_name='perevals',
            name='autumn_level',
        ),
        migrations.RemoveField(
            model_name='perevals',
            name='spring_level',
        ),
        migrations.RemoveField(
            model_name='perevals',
            name='summer_level',
        ),
        migrations.RemoveField(
            model_name='perevals',
            name='winter_level',
        ),
        migrations.AlterField(
            model_name='coords',
            name='height',
            field=models.IntegerField(verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='coords',
            name='latitude',
            field=models.FloatField(max_length=20, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='coords',
            name='longitude',
            field=models.FloatField(max_length=20, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='images',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Название изображения'),
        ),
        migrations.AlterField(
            model_name='perevalareas',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Название горы'),
        ),
        migrations.AlterField(
            model_name='perevals',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='perevals',
            name='beautyTitle',
            field=models.CharField(max_length=200, verbose_name='Общее название'),
        ),
        migrations.AlterField(
            model_name='perevals',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название перевала'),
        ),
        migrations.AlterField(
            model_name='spractivitiestypes',
            name='title',
            field=models.CharField(choices=[('MN', 'Горный'), ('HK', 'Пеший'), ('SK', 'Лыжный'), ('BK', 'Велосипедный'), ('MH', 'Горно-пеший')], max_length=128, verbose_name='Тип похода'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='full_name',
            field=models.CharField(max_length=128, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.IntegerField(unique=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='perevals',
            name='level_id',
            field=models.ForeignKey(default=('1b', '1Б'), on_delete=django.db.models.deletion.CASCADE, to='perevals.level'),
        ),
    ]
