# Generated by Django 4.2.7 on 2023-11-23 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perevals', '0002_level_remove_perevalareas_id_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevals',
            name='level_id',
            field=models.ForeignKey(default='1b', on_delete=django.db.models.deletion.CASCADE, to='perevals.level'),
        ),
    ]
